---
spec:
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject-secret-credentials: "secret/data/webapp/config"
        vault.hashicorp.com/agent-inject-template-credentials: |           
           {{ with secret "secret/data/webapp/config" -}}
               export USERNAME="{{ .Data.data.username }}"
               export PASSWORD="{{ .Data.data.password }}"
           {{- end }}

