---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  labels:
    app: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: app
        image: mskaesz/webapp-ruby:latest
        imagePullPolicy: Always
        env:
        - name: VAULT_ADDR
          value: "http://192.168.1.121:8200"
